# Site settings
title: Emma Tosch
email: etosch@cs.umass.edu
url: "http://cs.umass.edu/~etosch" 
twitter_username: emmatosch
github_username:  etosch
excerpt_separator: <!--summary-->
comments: true

# Build settings
markdown: kramdown
paginate: 5

gems:
- jekyll-lunr-js-search
- jekyll-paginate
- jekyll-mentions
